version: '3.9'

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: video-streaming-dynamodb
    ports:
      - "8000:8000"
    command: [ "-jar", "DynamoDBLocal.jar", "-sharedDb" ]
    volumes:
      - ./dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    restart: always
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: video-streaming-dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
    depends_on:
      - dynamodb
  minio:
    image: minio/minio
    container_name: video-streaming-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data:/data
    command: server --console-address ":9001" /data
  redis:
    image: redis:latest
    container_name: video-streaming-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    restart: always
    command: redis-server --appendonly yes
