/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.30.1
 * source: video.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace video {
  export enum VideoStatus {
    PUBLIC = 0,
    PRIVATE = 1,
    FAILED = 2,
  }
  export class UploadVideoRequest extends pb_1.Message {
    #one_of_decls: number[][] = [[1, 2, 3]];
    constructor(
      data?:
        | any[]
        | ({} & (
            | {
                metadata?: VideoMetadata;
                chunk?: never;
                thumbnail?: never;
              }
            | {
                metadata?: never;
                chunk?: Uint8Array;
                thumbnail?: never;
              }
            | {
                metadata?: never;
                chunk?: never;
                thumbnail?: Uint8Array;
              }
          )),
    ) {
      super();
      pb_1.Message.initialize(
        this,
        Array.isArray(data) ? data : [],
        0,
        -1,
        [],
        this.#one_of_decls,
      );
      if (!Array.isArray(data) && typeof data == "object") {
        if ("metadata" in data && data.metadata != undefined) {
          this.metadata = data.metadata;
        }
        if ("chunk" in data && data.chunk != undefined) {
          this.chunk = data.chunk;
        }
        if ("thumbnail" in data && data.thumbnail != undefined) {
          this.thumbnail = data.thumbnail;
        }
      }
    }
    get metadata() {
      return pb_1.Message.getWrapperField(
        this,
        VideoMetadata,
        1,
      ) as VideoMetadata;
    }
    set metadata(value: VideoMetadata) {
      pb_1.Message.setOneofWrapperField(this, 1, this.#one_of_decls[0], value);
    }
    get has_metadata() {
      return pb_1.Message.getField(this, 1) != null;
    }
    get chunk() {
      return pb_1.Message.getFieldWithDefault(
        this,
        2,
        new Uint8Array(0),
      ) as Uint8Array;
    }
    set chunk(value: Uint8Array) {
      pb_1.Message.setOneofField(this, 2, this.#one_of_decls[0], value);
    }
    get has_chunk() {
      return pb_1.Message.getField(this, 2) != null;
    }
    get thumbnail() {
      return pb_1.Message.getFieldWithDefault(
        this,
        3,
        new Uint8Array(0),
      ) as Uint8Array;
    }
    set thumbnail(value: Uint8Array) {
      pb_1.Message.setOneofField(this, 3, this.#one_of_decls[0], value);
    }
    get has_thumbnail() {
      return pb_1.Message.getField(this, 3) != null;
    }
    get data() {
      const cases: {
        [index: number]: "none" | "metadata" | "chunk" | "thumbnail";
      } = {
        0: "none",
        1: "metadata",
        2: "chunk",
        3: "thumbnail",
      };
      return cases[pb_1.Message.computeOneofCase(this, [1, 2, 3])];
    }
    static fromObject(data: {
      metadata?: ReturnType<typeof VideoMetadata.prototype.toObject>;
      chunk?: Uint8Array;
      thumbnail?: Uint8Array;
    }): UploadVideoRequest {
      const message = new UploadVideoRequest({});
      if (data.metadata != null) {
        message.metadata = VideoMetadata.fromObject(data.metadata);
      }
      if (data.chunk != null) {
        message.chunk = data.chunk;
      }
      if (data.thumbnail != null) {
        message.thumbnail = data.thumbnail;
      }
      return message;
    }
    toObject() {
      const data: {
        metadata?: ReturnType<typeof VideoMetadata.prototype.toObject>;
        chunk?: Uint8Array;
        thumbnail?: Uint8Array;
      } = {};
      if (this.metadata != null) {
        data.metadata = this.metadata.toObject();
      }
      if (this.chunk != null) {
        data.chunk = this.chunk;
      }
      if (this.thumbnail != null) {
        data.thumbnail = this.thumbnail;
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.has_metadata)
        writer.writeMessage(1, this.metadata, () =>
          this.metadata.serialize(writer),
        );
      if (this.has_chunk) writer.writeBytes(2, this.chunk);
      if (this.has_thumbnail) writer.writeBytes(3, this.thumbnail);
      if (!w) return writer.getResultBuffer();
    }
    static deserialize(
      bytes: Uint8Array | pb_1.BinaryReader,
    ): UploadVideoRequest {
      const reader =
          bytes instanceof pb_1.BinaryReader
            ? bytes
            : new pb_1.BinaryReader(bytes),
        message = new UploadVideoRequest();
      while (reader.nextField()) {
        if (reader.isEndGroup()) break;
        switch (reader.getFieldNumber()) {
          case 1:
            reader.readMessage(
              message.metadata,
              () => (message.metadata = VideoMetadata.deserialize(reader)),
            );
            break;
          case 2:
            message.chunk = reader.readBytes();
            break;
          case 3:
            message.thumbnail = reader.readBytes();
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): UploadVideoRequest {
      return UploadVideoRequest.deserialize(bytes);
    }
  }
  export class VideoMetadata extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(
      data?:
        | any[]
        | {
            title?: string;
            description?: string;
            extension?: string;
            duration?: number;
            thumbnailExtension?: string;
            status?: VideoStatus;
          },
    ) {
      super();
      pb_1.Message.initialize(
        this,
        Array.isArray(data) ? data : [],
        0,
        -1,
        [],
        this.#one_of_decls,
      );
      if (!Array.isArray(data) && typeof data == "object") {
        if ("title" in data && data.title != undefined) {
          this.title = data.title;
        }
        if ("description" in data && data.description != undefined) {
          this.description = data.description;
        }
        if ("extension" in data && data.extension != undefined) {
          this.extension = data.extension;
        }
        if ("duration" in data && data.duration != undefined) {
          this.duration = data.duration;
        }
        if (
          "thumbnailExtension" in data &&
          data.thumbnailExtension != undefined
        ) {
          this.thumbnailExtension = data.thumbnailExtension;
        }
        if ("status" in data && data.status != undefined) {
          this.status = data.status;
        }
      }
    }
    get title() {
      return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set title(value: string) {
      pb_1.Message.setField(this, 1, value);
    }
    get description() {
      return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set description(value: string) {
      pb_1.Message.setField(this, 2, value);
    }
    get extension() {
      return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set extension(value: string) {
      pb_1.Message.setField(this, 3, value);
    }
    get duration() {
      return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
    }
    set duration(value: number) {
      pb_1.Message.setField(this, 4, value);
    }
    get thumbnailExtension() {
      return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
    }
    set thumbnailExtension(value: string) {
      pb_1.Message.setField(this, 5, value);
    }
    get status() {
      return pb_1.Message.getFieldWithDefault(
        this,
        6,
        VideoStatus.PUBLIC,
      ) as VideoStatus;
    }
    set status(value: VideoStatus) {
      pb_1.Message.setField(this, 6, value);
    }
    static fromObject(data: {
      title?: string;
      description?: string;
      extension?: string;
      duration?: number;
      thumbnailExtension?: string;
      status?: VideoStatus;
    }): VideoMetadata {
      const message = new VideoMetadata({});
      if (data.title != null) {
        message.title = data.title;
      }
      if (data.description != null) {
        message.description = data.description;
      }
      if (data.extension != null) {
        message.extension = data.extension;
      }
      if (data.duration != null) {
        message.duration = data.duration;
      }
      if (data.thumbnailExtension != null) {
        message.thumbnailExtension = data.thumbnailExtension;
      }
      if (data.status != null) {
        message.status = data.status;
      }
      return message;
    }
    toObject() {
      const data: {
        title?: string;
        description?: string;
        extension?: string;
        duration?: number;
        thumbnailExtension?: string;
        status?: VideoStatus;
      } = {};
      if (this.title != null) {
        data.title = this.title;
      }
      if (this.description != null) {
        data.description = this.description;
      }
      if (this.extension != null) {
        data.extension = this.extension;
      }
      if (this.duration != null) {
        data.duration = this.duration;
      }
      if (this.thumbnailExtension != null) {
        data.thumbnailExtension = this.thumbnailExtension;
      }
      if (this.status != null) {
        data.status = this.status;
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.title.length) writer.writeString(1, this.title);
      if (this.description.length) writer.writeString(2, this.description);
      if (this.extension.length) writer.writeString(3, this.extension);
      if (this.duration != 0) writer.writeInt64(4, this.duration);
      if (this.thumbnailExtension.length)
        writer.writeString(5, this.thumbnailExtension);
      if (this.status != VideoStatus.PUBLIC) writer.writeEnum(6, this.status);
      if (!w) return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): VideoMetadata {
      const reader =
          bytes instanceof pb_1.BinaryReader
            ? bytes
            : new pb_1.BinaryReader(bytes),
        message = new VideoMetadata();
      while (reader.nextField()) {
        if (reader.isEndGroup()) break;
        switch (reader.getFieldNumber()) {
          case 1:
            message.title = reader.readString();
            break;
          case 2:
            message.description = reader.readString();
            break;
          case 3:
            message.extension = reader.readString();
            break;
          case 4:
            message.duration = reader.readInt64();
            break;
          case 5:
            message.thumbnailExtension = reader.readString();
            break;
          case 6:
            message.status = reader.readEnum();
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): VideoMetadata {
      return VideoMetadata.deserialize(bytes);
    }
  }
  export class UploadVideoResponse extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(
      data?:
        | any[]
        | {
            video_id?: string;
          },
    ) {
      super();
      pb_1.Message.initialize(
        this,
        Array.isArray(data) ? data : [],
        0,
        -1,
        [],
        this.#one_of_decls,
      );
      if (!Array.isArray(data) && typeof data == "object") {
        if ("video_id" in data && data.video_id != undefined) {
          this.video_id = data.video_id;
        }
      }
    }
    get video_id() {
      return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set video_id(value: string) {
      pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: { video_id?: string }): UploadVideoResponse {
      const message = new UploadVideoResponse({});
      if (data.video_id != null) {
        message.video_id = data.video_id;
      }
      return message;
    }
    toObject() {
      const data: {
        video_id?: string;
      } = {};
      if (this.video_id != null) {
        data.video_id = this.video_id;
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.video_id.length) writer.writeString(1, this.video_id);
      if (!w) return writer.getResultBuffer();
    }
    static deserialize(
      bytes: Uint8Array | pb_1.BinaryReader,
    ): UploadVideoResponse {
      const reader =
          bytes instanceof pb_1.BinaryReader
            ? bytes
            : new pb_1.BinaryReader(bytes),
        message = new UploadVideoResponse();
      while (reader.nextField()) {
        if (reader.isEndGroup()) break;
        switch (reader.getFieldNumber()) {
          case 1:
            message.video_id = reader.readString();
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): UploadVideoResponse {
      return UploadVideoResponse.deserialize(bytes);
    }
  }
  export class GetVideoRequest extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(
      data?:
        | any[]
        | {
            video_id?: string;
          },
    ) {
      super();
      pb_1.Message.initialize(
        this,
        Array.isArray(data) ? data : [],
        0,
        -1,
        [],
        this.#one_of_decls,
      );
      if (!Array.isArray(data) && typeof data == "object") {
        if ("video_id" in data && data.video_id != undefined) {
          this.video_id = data.video_id;
        }
      }
    }
    get video_id() {
      return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set video_id(value: string) {
      pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: { video_id?: string }): GetVideoRequest {
      const message = new GetVideoRequest({});
      if (data.video_id != null) {
        message.video_id = data.video_id;
      }
      return message;
    }
    toObject() {
      const data: {
        video_id?: string;
      } = {};
      if (this.video_id != null) {
        data.video_id = this.video_id;
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.video_id.length) writer.writeString(1, this.video_id);
      if (!w) return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GetVideoRequest {
      const reader =
          bytes instanceof pb_1.BinaryReader
            ? bytes
            : new pb_1.BinaryReader(bytes),
        message = new GetVideoRequest();
      while (reader.nextField()) {
        if (reader.isEndGroup()) break;
        switch (reader.getFieldNumber()) {
          case 1:
            message.video_id = reader.readString();
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): GetVideoRequest {
      return GetVideoRequest.deserialize(bytes);
    }
  }
  export class GetVideoResponse extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(
      data?:
        | any[]
        | {
            presigned_url?: string;
          },
    ) {
      super();
      pb_1.Message.initialize(
        this,
        Array.isArray(data) ? data : [],
        0,
        -1,
        [],
        this.#one_of_decls,
      );
      if (!Array.isArray(data) && typeof data == "object") {
        if ("presigned_url" in data && data.presigned_url != undefined) {
          this.presigned_url = data.presigned_url;
        }
      }
    }
    get presigned_url() {
      return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set presigned_url(value: string) {
      pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: { presigned_url?: string }): GetVideoResponse {
      const message = new GetVideoResponse({});
      if (data.presigned_url != null) {
        message.presigned_url = data.presigned_url;
      }
      return message;
    }
    toObject() {
      const data: {
        presigned_url?: string;
      } = {};
      if (this.presigned_url != null) {
        data.presigned_url = this.presigned_url;
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.presigned_url.length) writer.writeString(1, this.presigned_url);
      if (!w) return writer.getResultBuffer();
    }
    static deserialize(
      bytes: Uint8Array | pb_1.BinaryReader,
    ): GetVideoResponse {
      const reader =
          bytes instanceof pb_1.BinaryReader
            ? bytes
            : new pb_1.BinaryReader(bytes),
        message = new GetVideoResponse();
      while (reader.nextField()) {
        if (reader.isEndGroup()) break;
        switch (reader.getFieldNumber()) {
          case 1:
            message.presigned_url = reader.readString();
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): GetVideoResponse {
      return GetVideoResponse.deserialize(bytes);
    }
  }
  export class ListVideosRequest extends pb_1.Message {
    #one_of_decls: number[][] = [[1]];
    constructor(
      data?:
        | any[]
        | ({
            limit?: number;
          } & {
            last_evaluated_key?: string;
          }),
    ) {
      super();
      pb_1.Message.initialize(
        this,
        Array.isArray(data) ? data : [],
        0,
        -1,
        [],
        this.#one_of_decls,
      );
      if (!Array.isArray(data) && typeof data == "object") {
        if (
          "last_evaluated_key" in data &&
          data.last_evaluated_key != undefined
        ) {
          this.last_evaluated_key = data.last_evaluated_key;
        }
        if ("limit" in data && data.limit != undefined) {
          this.limit = data.limit;
        }
      }
    }
    get last_evaluated_key() {
      return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set last_evaluated_key(value: string) {
      pb_1.Message.setOneofField(this, 1, this.#one_of_decls[0], value);
    }
    get has_last_evaluated_key() {
      return pb_1.Message.getField(this, 1) != null;
    }
    get limit() {
      return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set limit(value: number) {
      pb_1.Message.setField(this, 2, value);
    }
    get _last_evaluated_key() {
      const cases: {
        [index: number]: "none" | "last_evaluated_key";
      } = {
        0: "none",
        1: "last_evaluated_key",
      };
      return cases[pb_1.Message.computeOneofCase(this, [1])];
    }
    static fromObject(data: {
      last_evaluated_key?: string;
      limit?: number;
    }): ListVideosRequest {
      const message = new ListVideosRequest({});
      if (data.last_evaluated_key != null) {
        message.last_evaluated_key = data.last_evaluated_key;
      }
      if (data.limit != null) {
        message.limit = data.limit;
      }
      return message;
    }
    toObject() {
      const data: {
        last_evaluated_key?: string;
        limit?: number;
      } = {};
      if (this.last_evaluated_key != null) {
        data.last_evaluated_key = this.last_evaluated_key;
      }
      if (this.limit != null) {
        data.limit = this.limit;
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.has_last_evaluated_key)
        writer.writeString(1, this.last_evaluated_key);
      if (this.limit != 0) writer.writeInt32(2, this.limit);
      if (!w) return writer.getResultBuffer();
    }
    static deserialize(
      bytes: Uint8Array | pb_1.BinaryReader,
    ): ListVideosRequest {
      const reader =
          bytes instanceof pb_1.BinaryReader
            ? bytes
            : new pb_1.BinaryReader(bytes),
        message = new ListVideosRequest();
      while (reader.nextField()) {
        if (reader.isEndGroup()) break;
        switch (reader.getFieldNumber()) {
          case 1:
            message.last_evaluated_key = reader.readString();
            break;
          case 2:
            message.limit = reader.readInt32();
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ListVideosRequest {
      return ListVideosRequest.deserialize(bytes);
    }
  }
  export class VideoInfo extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(
      data?:
        | any[]
        | {
            video_id?: string;
            title?: string;
            description?: string;
            thumbnail_url?: string;
            views?: number;
            likes?: number;
            duration?: number;
            status?: VideoStatus;
            created_at?: string;
          },
    ) {
      super();
      pb_1.Message.initialize(
        this,
        Array.isArray(data) ? data : [],
        0,
        -1,
        [],
        this.#one_of_decls,
      );
      if (!Array.isArray(data) && typeof data == "object") {
        if ("video_id" in data && data.video_id != undefined) {
          this.video_id = data.video_id;
        }
        if ("title" in data && data.title != undefined) {
          this.title = data.title;
        }
        if ("description" in data && data.description != undefined) {
          this.description = data.description;
        }
        if ("thumbnail_url" in data && data.thumbnail_url != undefined) {
          this.thumbnail_url = data.thumbnail_url;
        }
        if ("views" in data && data.views != undefined) {
          this.views = data.views;
        }
        if ("likes" in data && data.likes != undefined) {
          this.likes = data.likes;
        }
        if ("duration" in data && data.duration != undefined) {
          this.duration = data.duration;
        }
        if ("status" in data && data.status != undefined) {
          this.status = data.status;
        }
        if ("created_at" in data && data.created_at != undefined) {
          this.created_at = data.created_at;
        }
      }
    }
    get video_id() {
      return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set video_id(value: string) {
      pb_1.Message.setField(this, 1, value);
    }
    get title() {
      return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set title(value: string) {
      pb_1.Message.setField(this, 2, value);
    }
    get description() {
      return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set description(value: string) {
      pb_1.Message.setField(this, 3, value);
    }
    get thumbnail_url() {
      return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
    }
    set thumbnail_url(value: string) {
      pb_1.Message.setField(this, 4, value);
    }
    get views() {
      return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
    }
    set views(value: number) {
      pb_1.Message.setField(this, 5, value);
    }
    get likes() {
      return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
    }
    set likes(value: number) {
      pb_1.Message.setField(this, 6, value);
    }
    get duration() {
      return pb_1.Message.getFieldWithDefault(this, 7, 0) as number;
    }
    set duration(value: number) {
      pb_1.Message.setField(this, 7, value);
    }
    get status() {
      return pb_1.Message.getFieldWithDefault(
        this,
        8,
        VideoStatus.PUBLIC,
      ) as VideoStatus;
    }
    set status(value: VideoStatus) {
      pb_1.Message.setField(this, 8, value);
    }
    get created_at() {
      return pb_1.Message.getFieldWithDefault(this, 9, "") as string;
    }
    set created_at(value: string) {
      pb_1.Message.setField(this, 9, value);
    }
    static fromObject(data: {
      video_id?: string;
      title?: string;
      description?: string;
      thumbnail_url?: string;
      views?: number;
      likes?: number;
      duration?: number;
      status?: VideoStatus;
      created_at?: string;
    }): VideoInfo {
      const message = new VideoInfo({});
      if (data.video_id != null) {
        message.video_id = data.video_id;
      }
      if (data.title != null) {
        message.title = data.title;
      }
      if (data.description != null) {
        message.description = data.description;
      }
      if (data.thumbnail_url != null) {
        message.thumbnail_url = data.thumbnail_url;
      }
      if (data.views != null) {
        message.views = data.views;
      }
      if (data.likes != null) {
        message.likes = data.likes;
      }
      if (data.duration != null) {
        message.duration = data.duration;
      }
      if (data.status != null) {
        message.status = data.status;
      }
      if (data.created_at != null) {
        message.created_at = data.created_at;
      }
      return message;
    }
    toObject() {
      const data: {
        video_id?: string;
        title?: string;
        description?: string;
        thumbnail_url?: string;
        views?: number;
        likes?: number;
        duration?: number;
        status?: VideoStatus;
        created_at?: string;
      } = {};
      if (this.video_id != null) {
        data.video_id = this.video_id;
      }
      if (this.title != null) {
        data.title = this.title;
      }
      if (this.description != null) {
        data.description = this.description;
      }
      if (this.thumbnail_url != null) {
        data.thumbnail_url = this.thumbnail_url;
      }
      if (this.views != null) {
        data.views = this.views;
      }
      if (this.likes != null) {
        data.likes = this.likes;
      }
      if (this.duration != null) {
        data.duration = this.duration;
      }
      if (this.status != null) {
        data.status = this.status;
      }
      if (this.created_at != null) {
        data.created_at = this.created_at;
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.video_id.length) writer.writeString(1, this.video_id);
      if (this.title.length) writer.writeString(2, this.title);
      if (this.description.length) writer.writeString(3, this.description);
      if (this.thumbnail_url.length) writer.writeString(4, this.thumbnail_url);
      if (this.views != 0) writer.writeInt64(5, this.views);
      if (this.likes != 0) writer.writeInt64(6, this.likes);
      if (this.duration != 0) writer.writeInt64(7, this.duration);
      if (this.status != VideoStatus.PUBLIC) writer.writeEnum(8, this.status);
      if (this.created_at.length) writer.writeString(9, this.created_at);
      if (!w) return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): VideoInfo {
      const reader =
          bytes instanceof pb_1.BinaryReader
            ? bytes
            : new pb_1.BinaryReader(bytes),
        message = new VideoInfo();
      while (reader.nextField()) {
        if (reader.isEndGroup()) break;
        switch (reader.getFieldNumber()) {
          case 1:
            message.video_id = reader.readString();
            break;
          case 2:
            message.title = reader.readString();
            break;
          case 3:
            message.description = reader.readString();
            break;
          case 4:
            message.thumbnail_url = reader.readString();
            break;
          case 5:
            message.views = reader.readInt64();
            break;
          case 6:
            message.likes = reader.readInt64();
            break;
          case 7:
            message.duration = reader.readInt64();
            break;
          case 8:
            message.status = reader.readEnum();
            break;
          case 9:
            message.created_at = reader.readString();
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): VideoInfo {
      return VideoInfo.deserialize(bytes);
    }
  }
  export class ListVideosResponse extends pb_1.Message {
    #one_of_decls: number[][] = [[2]];
    constructor(
      data?:
        | any[]
        | ({
            videos?: VideoInfo[];
          } & {
            last_evaluated_key?: string;
          }),
    ) {
      super();
      pb_1.Message.initialize(
        this,
        Array.isArray(data) ? data : [],
        0,
        -1,
        [1],
        this.#one_of_decls,
      );
      if (!Array.isArray(data) && typeof data == "object") {
        if ("videos" in data && data.videos != undefined) {
          this.videos = data.videos;
        }
        if (
          "last_evaluated_key" in data &&
          data.last_evaluated_key != undefined
        ) {
          this.last_evaluated_key = data.last_evaluated_key;
        }
      }
    }
    get videos() {
      return pb_1.Message.getRepeatedWrapperField(
        this,
        VideoInfo,
        1,
      ) as VideoInfo[];
    }
    set videos(value: VideoInfo[]) {
      pb_1.Message.setRepeatedWrapperField(this, 1, value);
    }
    get last_evaluated_key() {
      return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set last_evaluated_key(value: string) {
      pb_1.Message.setOneofField(this, 2, this.#one_of_decls[0], value);
    }
    get has_last_evaluated_key() {
      return pb_1.Message.getField(this, 2) != null;
    }
    get _last_evaluated_key() {
      const cases: {
        [index: number]: "none" | "last_evaluated_key";
      } = {
        0: "none",
        2: "last_evaluated_key",
      };
      return cases[pb_1.Message.computeOneofCase(this, [2])];
    }
    static fromObject(data: {
      videos?: ReturnType<typeof VideoInfo.prototype.toObject>[];
      last_evaluated_key?: string;
    }): ListVideosResponse {
      const message = new ListVideosResponse({});
      if (data.videos != null) {
        message.videos = data.videos.map((item) => VideoInfo.fromObject(item));
      }
      if (data.last_evaluated_key != null) {
        message.last_evaluated_key = data.last_evaluated_key;
      }
      return message;
    }
    toObject() {
      const data: {
        videos?: ReturnType<typeof VideoInfo.prototype.toObject>[];
        last_evaluated_key?: string;
      } = {};
      if (this.videos != null) {
        data.videos = this.videos.map((item: VideoInfo) => item.toObject());
      }
      if (this.last_evaluated_key != null) {
        data.last_evaluated_key = this.last_evaluated_key;
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.videos.length)
        writer.writeRepeatedMessage(1, this.videos, (item: VideoInfo) =>
          item.serialize(writer),
        );
      if (this.has_last_evaluated_key)
        writer.writeString(2, this.last_evaluated_key);
      if (!w) return writer.getResultBuffer();
    }
    static deserialize(
      bytes: Uint8Array | pb_1.BinaryReader,
    ): ListVideosResponse {
      const reader =
          bytes instanceof pb_1.BinaryReader
            ? bytes
            : new pb_1.BinaryReader(bytes),
        message = new ListVideosResponse();
      while (reader.nextField()) {
        if (reader.isEndGroup()) break;
        switch (reader.getFieldNumber()) {
          case 1:
            reader.readMessage(message.videos, () =>
              pb_1.Message.addToRepeatedWrapperField(
                message,
                1,
                VideoInfo.deserialize(reader),
                VideoInfo,
              ),
            );
            break;
          case 2:
            message.last_evaluated_key = reader.readString();
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ListVideosResponse {
      return ListVideosResponse.deserialize(bytes);
    }
  }
  interface GrpcUnaryServiceInterface<P, R> {
    (
      message: P,
      metadata: grpc_1.Metadata,
      options: grpc_1.CallOptions,
      callback: grpc_1.requestCallback<R>,
    ): grpc_1.ClientUnaryCall;
    (
      message: P,
      metadata: grpc_1.Metadata,
      callback: grpc_1.requestCallback<R>,
    ): grpc_1.ClientUnaryCall;
    (
      message: P,
      options: grpc_1.CallOptions,
      callback: grpc_1.requestCallback<R>,
    ): grpc_1.ClientUnaryCall;
    (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
  }
  interface GrpcStreamServiceInterface<P, R> {
    (
      message: P,
      metadata: grpc_1.Metadata,
      options?: grpc_1.CallOptions,
    ): grpc_1.ClientReadableStream<R>;
    (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
  }
  interface GrpWritableServiceInterface<P, R> {
    (
      metadata: grpc_1.Metadata,
      options: grpc_1.CallOptions,
      callback: grpc_1.requestCallback<R>,
    ): grpc_1.ClientWritableStream<P>;
    (
      metadata: grpc_1.Metadata,
      callback: grpc_1.requestCallback<R>,
    ): grpc_1.ClientWritableStream<P>;
    (
      options: grpc_1.CallOptions,
      callback: grpc_1.requestCallback<R>,
    ): grpc_1.ClientWritableStream<P>;
    (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
  }
  interface GrpcChunkServiceInterface<P, R> {
    (
      metadata: grpc_1.Metadata,
      options?: grpc_1.CallOptions,
    ): grpc_1.ClientDuplexStream<P, R>;
    (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
  }
  interface GrpcPromiseServiceInterface<P, R> {
    (
      message: P,
      metadata: grpc_1.Metadata,
      options?: grpc_1.CallOptions,
    ): Promise<R>;
    (message: P, options?: grpc_1.CallOptions): Promise<R>;
  }
  export abstract class UnimplementedVideoServiceService {
    static definition = {
      UploadVideo: {
        path: "/video.VideoService/UploadVideo",
        requestStream: true,
        responseStream: false,
        requestSerialize: (message: UploadVideoRequest) =>
          Buffer.from(message.serialize()),
        requestDeserialize: (bytes: Buffer) =>
          UploadVideoRequest.deserialize(new Uint8Array(bytes)),
        responseSerialize: (message: UploadVideoResponse) =>
          Buffer.from(message.serialize()),
        responseDeserialize: (bytes: Buffer) =>
          UploadVideoResponse.deserialize(new Uint8Array(bytes)),
      },
      GetVideoURL: {
        path: "/video.VideoService/GetVideoURL",
        requestStream: false,
        responseStream: false,
        requestSerialize: (message: GetVideoRequest) =>
          Buffer.from(message.serialize()),
        requestDeserialize: (bytes: Buffer) =>
          GetVideoRequest.deserialize(new Uint8Array(bytes)),
        responseSerialize: (message: GetVideoResponse) =>
          Buffer.from(message.serialize()),
        responseDeserialize: (bytes: Buffer) =>
          GetVideoResponse.deserialize(new Uint8Array(bytes)),
      },
      ListVideos: {
        path: "/video.VideoService/ListVideos",
        requestStream: false,
        responseStream: false,
        requestSerialize: (message: ListVideosRequest) =>
          Buffer.from(message.serialize()),
        requestDeserialize: (bytes: Buffer) =>
          ListVideosRequest.deserialize(new Uint8Array(bytes)),
        responseSerialize: (message: ListVideosResponse) =>
          Buffer.from(message.serialize()),
        responseDeserialize: (bytes: Buffer) =>
          ListVideosResponse.deserialize(new Uint8Array(bytes)),
      },
    };
    [method: string]: grpc_1.UntypedHandleCall;
    abstract UploadVideo(
      call: grpc_1.ServerReadableStream<
        UploadVideoRequest,
        UploadVideoResponse
      >,
      callback: grpc_1.sendUnaryData<UploadVideoResponse>,
    ): void;
    abstract GetVideoURL(
      call: grpc_1.ServerUnaryCall<GetVideoRequest, GetVideoResponse>,
      callback: grpc_1.sendUnaryData<GetVideoResponse>,
    ): void;
    abstract ListVideos(
      call: grpc_1.ServerUnaryCall<ListVideosRequest, ListVideosResponse>,
      callback: grpc_1.sendUnaryData<ListVideosResponse>,
    ): void;
  }
  export class VideoServiceClient extends grpc_1.makeGenericClientConstructor(
    UnimplementedVideoServiceService.definition,
    "VideoService",
    {},
  ) {
    constructor(
      address: string,
      credentials: grpc_1.ChannelCredentials,
      options?: Partial<grpc_1.ChannelOptions>,
    ) {
      super(address, credentials, options);
    }
    UploadVideo: GrpWritableServiceInterface<
      UploadVideoRequest,
      UploadVideoResponse
    > = (
      metadata:
        | grpc_1.Metadata
        | grpc_1.CallOptions
        | grpc_1.requestCallback<UploadVideoResponse>,
      options?:
        | grpc_1.CallOptions
        | grpc_1.requestCallback<UploadVideoResponse>,
      callback?: grpc_1.requestCallback<UploadVideoResponse>,
    ): grpc_1.ClientWritableStream<UploadVideoRequest> => {
      return super.UploadVideo(metadata, options, callback);
    };
    GetVideoURL: GrpcUnaryServiceInterface<GetVideoRequest, GetVideoResponse> =
      (
        message: GetVideoRequest,
        metadata:
          | grpc_1.Metadata
          | grpc_1.CallOptions
          | grpc_1.requestCallback<GetVideoResponse>,
        options?: grpc_1.CallOptions | grpc_1.requestCallback<GetVideoResponse>,
        callback?: grpc_1.requestCallback<GetVideoResponse>,
      ): grpc_1.ClientUnaryCall => {
        return super.GetVideoURL(message, metadata, options, callback);
      };
    ListVideos: GrpcUnaryServiceInterface<
      ListVideosRequest,
      ListVideosResponse
    > = (
      message: ListVideosRequest,
      metadata:
        | grpc_1.Metadata
        | grpc_1.CallOptions
        | grpc_1.requestCallback<ListVideosResponse>,
      options?: grpc_1.CallOptions | grpc_1.requestCallback<ListVideosResponse>,
      callback?: grpc_1.requestCallback<ListVideosResponse>,
    ): grpc_1.ClientUnaryCall => {
      return super.ListVideos(message, metadata, options, callback);
    };
  }
}
