name: Auto Format TypeScript

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'frontend/**'
  push:
    branches:
      - master
    paths:
      - 'frontend/**'

jobs:
  test:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: yarn-${{ runner.os }}-${{ hashFiles('frontend/yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-

      - name: Install Dependencies
        run: |
          cd frontend
          yarn install --frozen-lockfile
          cd ..

      - name: Auto Format TypeScript
        run: |
          cd frontend
          yarn run fmt

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet
          then
            git add -A
            git commit -m "Auto format TypeScript code"
            git push
          fi
