name: Auto Format Go

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'api/**'
  push:
    branches:
      - master
    paths:
      - 'api/**'

jobs:
    test:
        permissions:
          contents: write
          pull-requests: write

        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                ref: ${{ github.head_ref }}

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.23'

            - name: Install dependencies
              env:
                GOIMPORTS_VERSION: 0.31.0
              run: go install golang.org/x/tools/cmd/goimports@v$GOIMPORTS_VERSION

            - name: Auto Format Go
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                goimports -w api
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                if ! git diff --quiet
                then
                  git add -A
                  git commit -m "auto format go"
                  git push
                fi
