name: Generate GRPC Code

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          cd frontend && yarn install
          cd ..

      - name: Generate GRPC Code for Go
        run: |
          protoc --proto_path=./proto --go_out=. --go-grpc_out=. video.proto

      - name: Generate GRPC Code for TypeScript
        run: |
          protoc --plugin=protoc-gen-ts=./frontend/node_modules/.bin/protoc-gen-ts --ts_out=./frontend/src/proto --proto_path=proto video.proto

      - name: Commit changes
        run: |
          TIMESTAMP=$(date)
          git config --global user.email "1898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b "generate-grpc-code-${TIMESTAMP}"
          git add .
          git commit -m "Generate GRPC Code"
          git push origin "generate-grpc-code-${TIMESTAMP}"

      - name: Create Pull Request
        run: |
          gh pr create --title "Generate GRPC Code" --body "Generate GRPC Code" --base master --head "generate-grpc-code-${TIMESTAMP}"
